- name: copy rabbit mq file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbit mq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start rabbit mq service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started

- name: add app user
  ansible.builtin.shell:
    rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"